name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag ghcr.io/sariandras/joke-client:0.1
        docker login ghcr.io -u sariandras -p ${{secrets.CR_TOKEN}}
        docker push ghcr.io/sariandras/joke-client:0.1
